version: '3.4'

services:
  linzi.site:
    image: linzi.site
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8081
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js